name: olist-causal
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - lightgbm
  - xgboost
  - statsmodels
  - pip
  - pip:
      - causalml
      - econml
      - pyarrow
